### PR TITLE
Fix non-empty meta when reading from shapefiles

### LINKED ISSUE #302: spatial_shuffle fails when loading from a shapefile
Calling `spatial_shuffle` on a `GeoDataFrame` that originates from a shapefile throws a `ValueError`. Below is an example that uses the attached shapefile:

```python
>>> import dask_geopandas as dgpd
>>> ddf = dgpd.read_file("example/example.shp", npartitions=1).spatial_shuffle()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fred/anaconda3/envs/dgpd-error/lib/python3.11/site-packages/dask_geopandas/expr.py", line 847, in spatial_shuffle
    sorted_ddf = self.set_index(
                 ^^^^^^^^^^^^^^^
  File "/home/fred/anaconda3/envs/dgpd-error/lib/python3.11/site-packages/dask_geopandas/expr.py", line 634, in set_index
    ddf = super().set_index(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fred/anaconda3/envs/dgpd-error/lib/python3.11/site-packages/dask_expr/_collection.py", line 3463, in set_index
    return new_collection(
           ^^^^^^^^^^^^^^^
  File "/home/fred/anaconda3/envs/dgpd-error/lib/python3.11/site-packages/dask_expr/_collection.py", line 4769, in new_collection
    meta = expr._meta
           ^^^^^^^^^^
  File "/home/fred/anaconda3/envs/dgpd-error/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/fred/anaconda3/envs/dgpd-error/lib/python3.11/site-packages/dask_expr/_shuffle.py", line 816, in _meta
    return self.frame._meta.set_index(other, drop=self.drop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fred/anaconda3/envs/dgpd-error/lib/python3.11/site-packages/pandas/core/frame.py", line 6173, in set_index
    raise ValueError(
ValueError: Length mismatch: Expected 5 rows, received array of length 0
```

Environment:
<details>

```sh
dask                      2024.6.2           pyhd8ed1ab_0    conda-forge
dask-core                 2024.6.2           pyhd8ed1ab_0    conda-forge
dask-expr                 1.1.6              pyhd8ed1ab_0    conda-forge
dask-geopandas            0.4.1              pyhd8ed1ab_0    conda-forge
geopandas                 1.0.0              pyhd8ed1ab_0    conda-forge
geopandas-base            1.0.0              pyha770c72_0    conda-forge
numpy                     2.0.0           py311h1461c94_0    conda-forge
pandas                    2.2.2           py311h14de704_1    conda-forge
```

</details>

[example.tar.gz](https://github.com/user-attachments/files/15995280/example.tar.gz)

### PR DESCRIPTION
**Pull request by fbunt**
Closes #302

### CODE REVIEW

**Comment by fbunt** [comment]
I added tests for the other reader types to be safe but I can pull them out if needed.

**Comment by fbunt** [comment]
Could someone review this?

**Comment by martinfleis** [comment]
Sorry for delays! This looks good. Can you also add a test that verifies that the erroneous line you had in #302 indeed works now?

**Comment by fbunt** [comment]
Sure! The error is triggered by a set_index operation with conflicting metas. I'll add a test for that. I can add a test for spatial_shuffle, too, if you think we need it.

**Comment by fbunt** [comment]
I added a test module for IO integration tests. Let me know if this is overkill.

**Review by martinfleis — APPROVED** [review]
Fine with me, thanks!

**Comment by fbunt** [comment]
Fixed

**Comment by fbunt** [comment]
Is it possible to do a patch release to get this out there?

**Comment by jorisvandenbossche** [comment]
@fbunt will look into doing a small bug-fix release tomorrow!

**Comment by fbunt** [comment]
Thanks!

**Comment by jorisvandenbossche** [comment]
FWIW, I was wondering if this should be considered a bug in dask-expr (that their `set_index` should not pass such meta object to pandas' set_index), but so dask does document `_meta` as always being empty (https://docs.dask.org/en/stable/dataframe-design.html?highlight=_meta#metadata). So regardless of this fix being a workaround for what dask-expr `set_index` does, creating empty meta objects seems to be what is expected.

@fbunt and thanks for the fix!

**Comment by fbunt** [comment]
Yeah it's tricky. I wasn't sure if that's how the rest of the _meta machinery works in dask/dask-expr.

**Pull request merged**
