### PR TITLE
FIX: set known shape on total_bounds result

### PR DESCRIPTION
**Pull request by martinfleis**
A potential solution to #74. I am just not sure what are the memory implications of `to_dask_array()`.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Can you check how the graph looks like on a small example? (eg like https://github.com/geopandas/dask-geopandas/pull/70#discussion_r666740079)

I am mainly wondering that by splitting it into multiple (separate) nanmin/max calls on the dask array, we might load the data multiple times.

**Comment by martinfleis** [comment]
Screenshot 2021-07-09 at 10 54 47

**Comment by martinfleis** [comment]
I am really not sure I am interpreting this correctly but I guess we're not loading data multiple times?

**Comment by martinfleis** [comment]
Just FYI, with this implementation, the only change to #70 required to avoid `compute()` is to remove it (cc @tastatham).

**Comment by jorisvandenbossche** [comment]
Hmm, not fully sure how to interpret that graph .. :)

I tried both the existing implementation and the one in this PR on a bigger dataset (OSM gps points, 114 million points, 1218 partitions in parquet), and the current implementation is a bit faster, but especially uses less memory. The one in this PR runs into max memory and needs to spill to disk some intermediate results (memory was limited artificially with dask to 4GB). The new implementation also gives a much bigger task graph (15042 tasks vs 2613 tasks).

I don't think the problem is that it's loading the data multiple times, but I think it is trying to keep the data in memory for a longer time. For the existing implementation, it reads a partitions, calculates the total bounds, keeps those 4 values and release the data, and then go to the next partition. _Maybe_ the problem with this implementation is that it doesn't understand that it should first calculate all min/max values for one partition before going to the next (it's a bit difficult to see because either it's a huge graph and the dashboard doesn't show it, or either I reduce the dataset but then I only have a few seconds to look at which tasks are waiting/processing/released in the graph in real time ;))

**Comment by jorisvandenbossche** [comment]
I think another solution to the original problem could be something like:

```
def total_bounds(self):
    ...
    total_bounds = self.reduction(..)
    return da.Array(total_bounds.dask, total_bounds.name, chunks=((4,),), dtype=total_bounds.dtype)
```

So basically rewrapping the graph in a new Array object but now with the chunk size set (you can also do `total_bounds._chunks = ((4,),)`, but that seems private API)

**Comment by martinfleis** [comment]
> So basically rewrapping the graph in a new Array object

I thought you also wanted to get rid of `reduction`? But I agree that the solution in this PR is not optimal.

**Comment by jorisvandenbossche** [comment]
> I thought you also wanted to get rid of `reduction`?

Yeah, the docstring doesn't mention this case as explicitly supported, but it seems to be working, so ..

**Comment by martinfleis** [comment]
Alright, let's go with the simple wrap of the current result in a dask array of a known shape. If the reduction will cause problems, we can revisit it later.

This solution also works within hilbert_distance without compute(). I guess the only issue there was an unknown shape.

**Comment by jorisvandenbossche** [comment]
This still has https://github.com/geopandas/dask-geopandas/issues/78 as problem (loading the full data), but let's already merge this for now.

**Pull request merged**
