### PR TITLE
BUG: fix ddf.set_geometry for geopandas main

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
See https://github.com/geopandas/dask-geopandas/issues/135#issuecomment-1019492684

This adds a `set_geometry` to dask.dataframe, similar as we do that in GeoPandas. However, that patching is also not super clean, so we might want to avoid it?

It is to fix this code snippet:

```
ddf = dd.from_pandas(df, npartitions=2)
ddf = dask_geopandas.from_dask_dataframe(ddf)
gddf = ddf.set_geometry(dask_geopandas.points_from_xy(ddf, "x", "y"))
```

Basically, in the above, the line `dask_geopandas.from_dask_dataframe(ddf)` has become "useless", as it still returns a dd.DataFrame. 

Instead of patching dd.DataFrame with `set_geometry`, another option could be to have the user do something like `dask_geopandas.from_dask_dataframe(ddf, geometry=dask_geopandas.points_from_xy(ddf, "x", "y"))`

### CODE REVIEW

**Comment by martinfleis** [comment]
> Instead of patching dd.DataFrame with set_geometry, another option could be to have the user do something like dask_geopandas.from_dask_dataframe(ddf, geometry=dask_geopandas.points_from_xy(ddf, "x", "y"))

This is exactly what I wanted to suggest. With the snippet above, the `ddf` after `dask_geopandas.from_dask_dataframe(ddf)` would be invalid anyway as it does not contain geometry. We should try to eb consistent with geopandas/geopandas#2060.

**Comment by jorisvandenbossche** [comment]
> With the snippet above, the `ddf` after `dask_geopandas.from_dask_dataframe(ddf)` would be invalid anyway as it does not contain geometry

Note that it is not actually an "invalid" dask_geopandas.GeoDataFrame, as it simply returns a "proper" dask.dataframe.DataFrame with pd.DataFrames as partitions. But of course that also makes the function a useless no-op (if there was not yet a geometry dtyped column).

**Comment by jorisvandenbossche** [comment]
You can compare it in this way: in geopandas, you can also create a GeoDataFrame in two ways if you start from a pandas.DataFrame:

```python
gdf = df.set_geometry(geometries)
# vs
gdf = geopandas.GeoDataFrame(df, geometry=geometries)
```

And in `dask_geopandas`, `from_dask_dataframe` is a bit the equivalent of the `geopandas.GeoDataFrame(..)` constructor in this case. 

Previously, you could also do this in geopandas:

```
gdf = geopandas.GeoDataFrame(df)
gdf = gdf.set_geometry(geometries)
```

this still works on geopandas main, but the first line will also actually return a DataFrame (if `df` doesn't have a geometry dtyped column), and the second like actually creates the GeoDataFrame and only works because geopandas patches pd.DataFrame with a `set_geometry` method.

**Comment by martinfleis** [comment]
> Note that it is not actually an "invalid" dask_geopandas.GeoDataFrame, as it simply returns a "proper" dask.dataframe.DataFrame with pd.DataFrames as partitions

Which surely is not what you expect from it. It essentially returns what you passed in.

**Comment by martinfleis** [comment]
I actually didn't know we can use `DataFrame.set_geometry`. It kind of feels wrong but I don't mind that.

We may actually want to do both here. Adding `set_geometry` to dask.DataFrame as you just did and expanding `from_dask_dataframe` to require `geometry` (to make sure it returns `dask_geopandas.GeoDataFrame`.

**Comment by jorisvandenbossche** [comment]
Updated to include both.

**Review by martinfleis — APPROVED** [review]
Thanks for the changes!

**Pull request merged**
