### PR TITLE
Remove PyGEOS support, require Shapely 2+

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
We don't actually have that much of code complexity from supporting both (at least not compared to pandas, because we mostly dispatch to the geopandas methods), but it does complicate testing a bit (e.g. when tests fail for pygeos), and generally I think shapely 2.0 is widely supported nowadays and already out for more than a year.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thoughts on adding `shapely>=2` to the dependencies in pyproject.toml? I suppose we get shapely through geopandas, but probably best to state it explicitly so that users don't need an ImportError to discover that their version isn't valid.

**Comment by martinfleis** [comment]
> If there are multiple geometry columns, are they guaranteed to have the same CRS? It seems like there's a CRS on the table but not a GeoSeries.

Yeah, we need that as the min geopandas is 0.12 which does not enforce shapely 2.

**Comment by jorisvandenbossche** [comment]
Good point to add shapely, done!

**Comment by TomAugspurger** [comment]
+1. The doc build failure looks related to dask-expr, which is being handled elsewhere.

**Pull request merged**
